### ISSUE TITLE
"the required version of java has not been installed"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jpcsp/jpcsp#326]
```
im trying to run jpcsp on win7 64bit and i get the followin message:
"the required version of java has not been installed.go to java.sun.com and 
download 64bit java JRE"
and that's what i did and it was successfully installed but when i run jpcsp 
nothing change...what can i do?

```

Original issue reported on code.google.com by `pirateki...@live.fr` on 4 Nov 2012 at 10:21

**Comment by HeroineChan** [comment]
Why those became like this?
![untitled](https://cloud.githubusercontent.com/assets/16014270/11607218/eaf21fbc-9b78-11e5-9f39-89856db4f241.png)
![untitled 1](https://cloud.githubusercontent.com/assets/16014270/11607219/eaf5a86c-9b78-11e5-9f4e-ed1c6a9aae09.png)
