### ISSUE TITLE
This jpcsp repository should be moved into jpcsp organization

### ISSUE THREAD

**Issue by hlide** [jpcsp/jpcsp#386]
It's not correct for the other authors even they were past members. JPCSP Team are the original authors who contributed in the SVN version so I would expect the source to go to the right organization, especially when the old SVN repository is not even available now. And it also seems the SVN export is not done properly since we can see our email addresses but not linking to our GitHub nicknames.

**Comment by Hykem** [comment]
Closing this issue since it has been resolved.
