### ISSUE TITLE
Updated translation to brazilian portuguese

### ISSUE THREAD

**Issue by Felipefpl** [jpcsp/jpcsp#403]
Hi, here is the update of my translation to pt-br compressed with 7zip 9.20 64 bit and made based on the latest build.

http://ge.tt/api/1/files/1EDjPkS2/0/blob?download

Btw, i noticed Orphis stopped doing builds, what happened? It's better to download from him than rapidgator.

**Comment by gid15** [comment]
Now added by ec5d45f. Sorry for the long delay...
Remark: it would be better to send a Pull request if you have similar changes in the future...
