### ISSUE TITLE
ControlsGUI issue

### ISSUE THREAD

**Issue by lightfirst** [jpcsp/jpcsp#405]
Get very bad control lag after change control settings. It will be ok after re-runing JPCSP though.
After I change ControlsGUI.java line 956:  setVisible(false); back to  dispose();  the lag was gone. But I can only change once control settings when JPCSP is running.

**Comment by gid15** [comment]
For me, the issue seems to now be fixed with 9f834b0.
Could you also check it?

Thank you

**Comment by lightfirst** [comment]
@gid15 
It help control lag.
But the 2nd time I open ControlsGUI, I try change control settings again, only keyboard key can be set, I press the button on my gamepad, nothing happend

**Comment by gid15** [comment]
OK, I didn't test the gamepad. It should now be fixed in ee38e26.

**Comment by lightfirst** [comment]
think you, now Control working fine

![5](https://cloud.githubusercontent.com/assets/4612168/12806219/e5e1810c-cb3e-11e5-9ab7-cf8a5eec3515.PNG)

**Comment by gid15** [comment]
Is it a new problem or did it always look like that in the past?

**Comment by lightfirst** [comment]
very old problem, since when I know jpcsp.

**Comment by sum2012** [comment]
No more problem ?
Press close issue in the buttom
