### ISSUE TITLE
The Red Star [NPUH10040] No sound 

### ISSUE THREAD

**Issue by lightfirst** [jpcsp/jpcsp#408]
The older ver have sound.
first broken commit    f25f23fecb6e4f0870b50ad1314537b2760ed66e

**Comment by gid15** [comment]
Is it improved by 91a3ea9? If not, I would need a log file at DEBUG level for hle.sceSasCore.

**Comment by lightfirst** [comment]
https://github.com/jpcsp/jpcsp/commit/91a3ea9a211fa50f2e549db8e47ac5cc62be1944  have Sound but bgm will disappear after 5 seconds
Enable sceSasCore DEBUG level, the game and sound will slow but bgm not disappear. 
[DEBUG log.zip](https://github.com/jpcsp/jpcsp/files/179629/DEBUG.log.zip)

**Comment by gid15** [comment]
I've fixed an issue in a6c19f1. Not sure if that would help here. What is strange is that the BGM does not disappear when enabling sceSasCore at DEBUG level...

**Comment by lightfirst** [comment]
NOT help
[DEBUG-log2.ZIP](https://github.com/jpcsp/jpcsp/files/180717/DEBUG-log2.ZIP)

**Comment by sum2012** [comment]
I do not have problem without enable debug log with https://github.com/jpcsp/jpcsp/commit/a6c19f1de3c93b40d7cd72cb7beee234bda0565d commit

**Comment by lightfirst** [comment]
I try clean and rebuild JPCSP, after that BGM is ok

**Comment by sum2012** [comment]
Press close issue in the buttom
