### ISSUE TITLE
CSO - image size in bytes, max 2 GB

### ISSUE THREAD

**Issue by adiantek** [jpcsp/jpcsp#415]
https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/filesystems/umdiso/CSOFileSectorDevice.java#L48

    int lengthInBytes = byteBuffer.getInt(8);
should be:

    long lengthInBytes = byteBuffer.getLong(4);

It should be long. First four bytes is "CISO", next 8 bytes is size as long, not skip 4 bytes and read int.

**Comment by gid15** [comment]
Thank you!
Now fixed in fa2c0f1.

Rem.: getLong can't be used as the ByteOrder is little-endian but the 32-bit at offset 4 are actually the highest 32-bit of the long value.
