### ISSUE TITLE
Shaders can't compile with mesa3d open source linux driver 

### ISSUE THREAD

**Issue by mrcmunir** [jpcsp/jpcsp#429]
>
10166 [GUI] INFO  ge - Using RenderingEngineLwjgl15
10167 [GUI] INFO  ge - Using VBO
ge - OpenGL version: 3.0 Mesa 17.0.0-devel (git-3a8f316e7b)
10168 [GUI] INFO  ge - Shading Language version: 1.30
10168 [GUI] INFO  ge - GL_CONTEXT_FLAGS: 0x0
10201 [GUI] INFO  ge - Using VAO (Vertex Array Object)
10202 [GUI] INFO  ge - Using shaders with Skinning
10202 [GUI] INFO  ge - Using dynamic shaders
10204 [GUI] INFO  ge - Using Uniform Buffer Object (UBO)
10209 [GUI] INFO  ge - Extension GL_EXT_gpu_shader4 not available: not using bit operators in shader
10220 [GUI] ERROR ge - Shader error log: 0:1(10): error: GLSL 3.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

Also some function glMatrix are unlike because they no supported for depcrecated functions in Opengl 3.0+ no compatibility profile.

Exception in thread "GUI" java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL11.glMatrixMode(GL11.java:2075)
	at jpcsp.graphics.RE.RenderingEngineLwjgl.setMatrixMode(RenderingEngineLwjgl.java:1376)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setMatrixMode(BaseRenderingEngineProxy.java:237)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setMatrixMode(BaseRenderingEngineProxy.java:237)
	at jpcsp.graphics.RE.StateProxy.setMatrixMode(StateProxy.java:827)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setMatrixMode(BaseRenderingEngineProxy.java:237)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setMatrixMode(BaseRenderingEngineProxy.java:237)
	at jpcsp.graphics.RE.RenderingEngineLwjgl.setProjectionMatrix(RenderingEngineLwjgl.java:1335)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setProjectionMatrix(BaseRenderingEngineProxy.java:277)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setProjectionMatrix(BaseRenderingEngineProxy.java:277)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setProjectionMatrix(BaseRenderingEngineProxy.java:277)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.setProjectionMatrix(BaseRenderingEngineProxy.java:277)
	at jpcsp.graphics.RE.BaseRenderingEngineFunction.startDirectRendering(BaseRenderingEngineFunction.java:384)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.startDirectRendering(BaseRenderingEngineProxy.java:77)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.startDirectRendering(BaseRenderingEngineProxy.java:77)
	at jpcsp.graphics.RE.BaseRenderingEngineProxy.startDirectRendering(BaseRenderingEngineProxy.java:77)
	at jpcsp.graphics.RE.ViewportFilter.startDirectRendering(ViewportFilter.java:72)
	at jpcsp.graphics.textures.GETexture.drawTexture(GETexture.java:225)
	at jpcsp.graphics.textures.GETexture.copyTextureToScreen(GETexture.java:221)
	at jpcsp.graphics.textures.GETexture.copyTextureToScreen(GETexture.java:211)
	at jpcsp.HLE.modules.sceDisplay$AWTGLCanvas_sceDisplay.paintGL(sceDisplay.java:325)
	at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:339)
	at org.lwjgl.opengl.AWTGLCanvas.update(AWTGLCanvas.java:368)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.awt.X11.XRepaintArea.updateComponent(XRepaintArea.java:51)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by mrcmunir** [comment]
If I found with force #version 130 in shader.frag and shader.vert

The error ERROR ge - Shader error log: 0:1(10): error: GLSL is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES no reproduced but the perfomance no diferences with shaders ON/OFF 

In next days will research what change broken/perfomance issues cause this regresion

**Comment by mrcmunir** [comment]
Well in the actual driver code never working shaders 

Force Opengl GL 3.2FC with export MESA_GL_VERSION_OVERRIDE=3.2FC and GLSL is 140 and higher..

Return a lot error 

-> 9609 [GUI] ERROR ge - Shader error log: 0:114(12): error: `gl_LightSource' undeclared
0:114(12): error: type mismatch
0:114(12): error: type mismatch
0:115(11): error: `gl_LightSource' undeclared
0:115(11): error: type mismatch
0:115(11): error: type mismatch
0:115(48): warning: `w' used uninitialized
0:115(11): error: operands to arithmetic operators must be numeric
0:116(11): warning: `L' used uninitialized
0:118(34): warning: `L' used uninitialized
0:120(12): error: `gl_FrontMaterial' undeclared
0:120(12): error: type mismatch
0:121(54): warning: `k' used uninitialized
0:122(54): warning: `k' used uninitialized
0:124(6): warning: `w' used uninitialized
0:126(19): warning: `L' used uninitialized
0:127(21): error: `gl_LightSource' undeclared
0:127(21): error: type mismatch
0:127(62): error: `gl_LightSource' undeclared
0:127(62): error: type mismatch
0:127(100): error: `gl_LightSource' undeclared
0:127(100): error: type mismatch
0:127(100): error: operands to arithmetic operators must be numeric
0:127(62): error: operands to arithmetic operators must be numeric
0:127(61): error: operands to arithmetic operators must be numeric
0:127(21): error: operands to arithmetic operators must be numeric
0:127(14): error: operands to arithmetic operators must be numeric
0:127(8): error: no matching function for call to `clamp(error, float, float)'; candidates are:
0:127(8): error:    float clamp(float, float, float)
0:127(8): error:    vec2 clamp(vec2, float, float)
0:127(8): error:    vec3 clamp(vec3, float, float)
0:127(8): error:    vec4 clamp(vec4, float, float)
0:127(8): error:    vec2 clamp(vec2, vec2, vec2)
0:127(8): error:    vec3 clamp(vec3, vec3, vec3)
0:127(8): error:    vec4 clamp(vec4, vec4, vec4)
0:127(8): error:    int clamp(int, int, int)
0:127(8): error:    ivec2 clamp(ivec2, int, int)
0:127(8): error:    ivec3 clamp(ivec3, int, int)
0:127(8): error:    ivec4 clamp(ivec4, int, int)
0:127(8): error:    ivec2 clamp(ivec2, ivec2, ivec2)
0:127(8): error:    ivec3 clamp(ivec3, ivec3, ivec3)
0:127(8): error:    ivec4 clamp(ivec4, ivec4, ivec4)
0:127(8): error:    uint clamp(uint, uint, uint)
0:127(8): error:    uvec2 clamp(uvec2, uint, uint)
0:127(8): error:    uvec3 clamp(uvec3, uint, uint)
0:127(8): error:    uvec4 clamp(uvec4, uint, uint)
0:127(8): error:    uvec2 clamp(uvec2, uvec2, uvec2)
0:127(8): error:    uvec3 clamp(uvec3, uvec3, uvec3)
0:127(8): error:    uvec4 clamp(uvec4, uvec4, uvec4)
0:128(6): error: `gl_LightSource' undeclared
0:128(6): error: type mismatch
0:128(6): error: operands to relational operators must be scalar and numeric
0:128(6): error: if-statement condition must be scalar boolean
0:130(29): error: `gl_LightSource' undeclared
0:130(29): error: type mismatch
0:130(29): error: type mismatch
0:130(19): error: no matching function for call to `normalize(error)'; candidates are:
0:130(19): error:    float normalize(float)
0:130(19): error:    vec2 normalize(vec2)
0:130(19): error:    vec3 normalize(vec3)
0:130(19): error:    vec4 normalize(vec4)
0:130(68): warning: `L' used uninitialized
0:130(15): error: no matching function for call to `dot(error, vec3)'; candidates are:
0:130(15): error:    float dot(float, float)
0:130(15): error:    float dot(vec2, vec2)
0:130(15): error:    float dot(vec3, vec3)
0:130(15): error:    float dot(vec4, vec4)
0:131(10): warning: `spot' used uninitialized
0:131(17): error: `gl_LightSource' undeclared
0:131(17): error: type mismatch
0:131(10): error: operands to relational operators must be scalar and numeric
0:131(10): error: condition of `?:' must be scalar boolean
0:131(68): error: `gl_LightSource' undeclared
0:131(68): error: type mismatch
0:131(58): error: no matching function for call to `pow(float, error)'; candidates are:
0:131(58): error:    float pow(float, float)
0:131(58): error:    vec2 pow(vec2, vec2)
0:131(58): error:    vec3 pow(vec3, vec3)
0:131(58): error:    vec4 pow(vec4, vec4)
0:131(52): error: second and third operands of ?: operator must have matching types
0:134(7): error: `gl_LightSource' undeclared
0:134(7): error: type mismatch
0:134(7): error: type mismatch
0:134(7): error: operands to arithmetic operators must be numeric
0:134(2): error: operands to arithmetic operators must be numeric
0:134(2): error: could not implicitly convert error to vec3
0:135(7): error: `gl_LightSource' undeclared
0:135(7): error: type mismatch
0:135(7): error: type mismatch
0:135(7): error: operands to arithmetic operators must be numeric
0:135(7): error: operands to arithmetic operators must be numeric
0:135(2): error: operands to arithmetic operators must be numeric
0:135(2): error: could not implicitly convert error to vec3
0:136(7): error: `gl_LightSource' undeclared
0:136(7): error: type mismatch
0:136(7): error: type mismatch
0:136(7): error: operands to arithmetic operators must be numeric
0:136(7): error: operands to arithmetic operators must be numeric
0:136(2): error: operands to arithmetic operators must be numeric
0:136(2): error: could not implicitly convert error to vec3
0:141(12): error: `gl_FrontMaterial' undeclared
0:141(12): error: type mismatch
0:141(12): error: type mismatch
0:143(45): error: `gl_FrontMaterial' undeclared
0:143(45): error: type mismatch
0:143(45): error: type mismatch
0:143(35): error: second and third operands of ?: operator must have matching types
0:144(44): error: `gl_FrontMaterial' undeclared
0:144(44): error: type mismatch
0:144(44): error: type mismatch
0:144(35): error: second and third operands of ?: operator must have matching types
0:145(44): error: `gl_FrontMaterial' undeclared
0:145(44): error: type mismatch
0:145(44): error: type mismatch
0:145(35): error: second and third operands of ?: operator must have matching types
0:164(12): error: `gl_LightModel' undeclared
0:164(12): error: type mismatch
0:169(54): warning: `Al' used uninitialized
0:204(17): warning: `Em' used uninitialized
0:204(31): warning: `Am' used uninitialized
0:204(45): warning: `Dm' used uninitialized
0:205(22): warning: `Sm' used uninitialized
0:209(17): warning: `Em' used uninitialized
0:209(31): warning: `Am' used uninitialized
0:209(45): warning: `Dm' used uninitialized
0:209(55): warning: `Sm' used uninitialized
0:217(16): warning: `Am' used uninitialized
0:235(20): error: `gl_TextureMatrix' undeclared
0:235(20): error: operands to arithmetic operators must be numeric
0:235(15): error: cannot construct `vec2' from a non-numeric data type
0:235(10): error: cannot construct `vec3' from a non-numeric data type
0:242(15): error: `gl_TextureMatrix' undeclared
0:242(15): error: operands to arithmetic operators must be numeric
0:242(10): error: cannot construct `vec3' from a non-numeric data type
0:245(15): error: `gl_TextureMatrix' undeclared
0:245(15): error: operands to arithmetic operators must be numeric
0:245(10): error: cannot construct `vec3' from a non-numeric data type
0:248(15): error: `gl_TextureMatrix' undeclared
0:248(15): error: operands to arithmetic operators must be numeric
0:248(10): error: cannot construct `vec3' from a non-numeric data type
0:251(15): error: `gl_TextureMatrix' undeclared
0:251(15): error: operands to arithmetic operators must be numeric
0:251(10): error: cannot construct `vec3' from a non-numeric data type
0:258(17): error: `gl_ModelViewMatrix' undeclared
0:258(17): error: operands to arithmetic operators must be numeric
0:258(12): error: cannot construct `vec3' from a non-numeric data type
0:259(12): error: `gl_FrontMaterial' undeclared
0:259(12): error: type mismatch
0:260(12): error: `gl_LightSource' undeclared
0:260(12): error: type mismatch
0:260(12): error: type mismatch
0:260(54): warning: `Ve' used uninitialized
0:260(63): error: `gl_LightSource' undeclared
0:260(63): error: type mismatch
0:260(63): error: type mismatch
0:260(54): error: operands to arithmetic operators must be numeric
0:260(12): error: operands to arithmetic operators must be numeric
0:261(12): error: `gl_LightSource' undeclared
0:261(12): error: type mismatch
0:261(12): error: type mismatch
0:261(54): warning: `Ve' used uninitialized
0:261(63): error: `gl_LightSource' undeclared
0:261(63): error: type mismatch
0:261(63): error: type mismatch
0:261(54): error: operands to arithmetic operators must be numeric
0:261(12): error: operands to arithmetic operators must be numeric
0:262(64): warning: `Lu' used uninitialized
0:262(93): warning: `Lu' used uninitialized
0:262(121): warning: `k' used uninitialized
0:263(64): warning: `Lv' used uninitialized
0:263(93): warning: `Lv' used uninitialized
0:263(121): warning: `k' used uninitialized
0:608(17): error: `gl_ModelViewMatrix' undeclared
0:608(17): error: operands to arithmetic operators must be numeric
0:608(12): error: cannot construct `vec3' from a non-numeric data type
0:611(6): error: `gl_NormalMatrix' undeclared
0:611(6): error: operands to arithmetic operators must be numeric
0:615(44): warning: `Ve' used uninitialized
0:626(16): error: `gl_ModelViewProjectionMatrix' undeclared
0:626(16): error: operands to arithmetic operators must be numeric
0:627(2): error: `gl_FogFragCoord' undeclared
0:627(20): warning: `Ve' used uninitialized
0:627(2): error: value of type float cannot be assigned to variable of type error
0:628(2): error: `gl_TexCoord' undeclared
0:628(2): error: value of type vec4 cannot be assigned to variable of type error
0:629(2): error: `gl_FrontColor' undeclared
0:629(2): error: value of type vec4 cannot be assigned to variable of type error
0:630(2): error: `gl_FrontSecondaryColor' undeclared
0:630(2): error: value of type vec4 cannot be assigned to variable of type error

If I Force  export MESA_GLSL_VERSION_OVERRIDE=130 with higher version than Opengl30

9773 [GUI] ERROR ge - Shader error log: 0:232(2): error: illegal use of reserved word `switch'
0:232(2): error: syntax error, unexpected ERROR_TOK

hmmm @gid15 any idea work shader with mesa3d?

**Comment by gid15** [comment]
You are using a developer version from mesa3d:
OpenGL version: 3.0 Mesa 17.0.0-devel (git-3a8f316e7b)

Have you tried a stable version? From what I read on their site, the version 17 is still far from being complete.

**Comment by mrcmunir** [comment]
@gid15 Yes I tried with the stable last 13.0 stable (mesa-13.0.3-1) not helped same errors .

**Comment by gid15** [comment]
You are writing about a "regression error". Does it mean it already worked in the past?

**Comment by mrcmunir** [comment]
@gid15 The workaround  Is added #version 130 in .vert and .frag files no GLSL fault unsupported this workarround is with Opengl 3.0 core.

In Very old JPCSP early JWLGL need disable GL_EXT_GPU_Shader4 because not supported in mesa3d.

With #version 120 or if use LWLGRenderOpengl31 returns fault 

9578 [GUI] ERROR ge - Shader error log: 0:232(2): error: illegal use of reserved word `switch'
0:232(2): error: syntax error, unexpected ERROR_TOK

With #version 130 No errors in the log with LWLGLRenderOpengl15

With #version 140 and Opengl31+ core and higher no support for Deprecated functions undeclarated similar problem in Mac OS X for Opengl 3.1 and higher .

The recomandation is needed restructure for Opengl31 and higher rewrite deprecate functions for Opengl 3.3 Core beucase this is problematic for mesa3d and Mac Os x S.O in nowadays.

http://stackoverflow.com/questions/27649926/use-of-undeclared-identifier-gl-lightsource

**Comment by mrcmunir** [comment]
It's fixed with updated LWJGL .
