### ISSUE TITLE
JpcspTrace not detected on psp 3000

### ISSUE THREAD

**Issue by benderscruffy** [jpcsp/jpcsp#446]
i have a psp with cfw 6.61 
i have copied the files onto my psp into the rightr directories and added the line to game .txt but for some reason it is not logging the syscalls

**Comment by gid15** [comment]
I do not own a PSP 3000 but I will try to reproduce it on Jpcsp itself, using Low Level Emulation (LLE). But this is still experimental, not sure if it will work...

**Comment by gid15** [comment]
Could you please try with the following 2 files? I have removed a dependency to the module "sceAta_driver" which might not be available on a PSP 3000 with PRO-C CFW?

Thank you!


[JpcspTrace.zip](https://github.com/jpcsp/jpcsp/files/3221036/JpcspTrace.zip)

**Comment by benderscruffy** [comment]
yes that works now
