### ISSUE TITLE
Is there an Android version of jpcsp?

### ISSUE THREAD

**Issue by lexterror** [jpcsp/jpcsp#450]
Hi,

I wanted to know if there is or will be an android version of JPCSP.

Thank you!

**Comment by gid15** [comment]
Hi,

an android version of Jpcsp is not planned by myself. It seems nobody else has time to work on it...

**Comment by Gamemulatorer** [comment]
There is a ppsspp that support android platform.

**Comment by lexterror** [comment]
JPCSP has better compatibility with some games than ppsspp

**Comment by Gamemulatorer** [comment]
> JPCSP has better compatibility with some games than ppsspp

I don't think so 😅

**Comment by MojoJojoDojo** [comment]
> > JPCSP has better compatibility with some games than ppsspp
> 
> I don't think so 😅

It does actually for adhoc/multiplayer games.

**Comment by gid15** [comment]
Closing as the question was answered.
