### ISSUE TITLE
Full support for kirk4/7 ?

### ISSUE THREAD

**Issue by zecoxao** [jpcsp/jpcsp#454]
Now that all kirk 4/7 128 keys have been dumped, i guess it's time for full support?
see https://github.com/ProximaV/kirk-engine-full

**Comment by gid15** [comment]
Thank you for the information.
The keys for Kirk 4/7 have already been added, but the implementation of other Kirk commands is still incomplete (mainly related to ECDSA: commands 12/13/16/17). I am working on those.

**Comment by zecoxao** [comment]
ok, thanks for answering :)
keep up the good work

**Comment by gid15** [comment]
libkirk has been ported to Java and integrated into Jpcsp.
