### ISSUE TITLE
Battery problem

### ISSUE THREAD

**Issue by VirtualPedestrian** [jpcsp/jpcsp#458]
Sorry if I'm ruining your day by asking you a dumb question, using bad grammar or not using a screenshot but my JPCSP can't update ofw because of battery problem 
![IMG_20201210_134648](https://user-images.githubusercontent.com/73787177/101726992-9c123b00-3aee-11eb-8933-1df3ce61a89b.jpg)

**Comment by gid15** [comment]
If you use a Laptop running on Windows, Jpcsp is simulating the charge of the PSP battery using the charge of the Laptop battery. So, charge your Laptop battery and retry.

**Comment by VirtualPedestrian** [comment]
Thanks man BTW is there a way to run xmb without dumping psp
