### ISSUE TITLE
lack of decompression algos (kl4e, kl3e) written in native java

### ISSUE THREAD

**Issue by zecoxao** [jpcsp/jpcsp#463]
now that these algos are properly written in C (thanks to the amazing work of artart78 and John-K), see:
https://github.com/John-K/pspdecrypt/blob/master/kl4e.c
https://github.com/John-K/pspdecrypt/blob/master/kl4e.h

and
https://github.com/John-K/pspdecrypt/blob/master/libLZR.c
https://github.com/John-K/pspdecrypt/blob/master/libLZR.h

i do believe it's time instead of the emulator, an actual java implementation would be done for jpcsp :)

**Comment by gid15** [comment]
Thank you for the information! I will have a look at it.

**Comment by gid15** [comment]
Added in da8a727.
I will cleanup the old code retrieving the kl4e/kl3e decompressors from the prx's later, after doing more testing.
