### ISSUE TITLE
Feature request: Adding string support to the debugger

### ISSUE THREAD

**Issue by codedwrench** [jpcsp/jpcsp#468]
Something I noticed I am missing when debugging with JPCSP is that I don't see the output of a string when running the debugger. Is it possible to add this?

**Comment by gid15** [comment]
Are you talking about the Debugger UI (menu Debug/Tools/Debugger)?
The Memory viewer (menu Debug/Tools/Memory viewer) is already displaying bytes as strings. I guess you would like to have a quicker link between the Debugger GPR register values and the Memory viewer, right? E.g. update automatically the Memory viewer to the address pointed by a register value when selecting that register.
Would it help or do you have another idea?

**Comment by codedwrench** [comment]
That would help a lot already, but what I'm really thinking of is the following: 
![image](https://user-images.githubusercontent.com/9693338/115418131-87ab2100-a1f9-11eb-98ec-6e9853a664ff.png)

It recognizes a string being loaded in and displays it, this debugger does it: http://ppsspp-debugger.unknownbrackets.org/ 

However being able to point to the memory view at a register level would be very good too!

**Comment by gid15** [comment]
I've implemented a first draft in bc3fc5a:
- when double-clicking on a register name, display the memory pointed by that register into the memory viewer.
- display register values (and pointed memory bytes or string value) into the debugger status line.

**Comment by codedwrench** [comment]
Seems to work well enough, double clicking on registers is very useful :+1:
