### ISSUE TITLE
Cant install 6.61 on v0.7 3712:3736

### ISSUE THREAD

**Issue by yarik3032** [jpcsp/jpcsp#474]
It just dont go with error java.lang.IndexOutOfBoundsException

**Comment by gid15** [comment]
Jpcsp r3736 is from March 2015... Please try with the latest release.

**Comment by yarik3032** [comment]
sorry but latest just crash from github or from another?

**Comment by gid15** [comment]
Have you tried the release available on github?

https://github.com/jpcsp/jpcsp/releases/tag/XLinkKai-v1.0

There are a few changes that came later, but I can't say if those were affecting the installation of 6.61.

**Comment by gid15** [comment]
It is working when using the latest releases. This has been confirmed by several users.
Hence, closing this issue.
