### ISSUE TITLE
CSO made with maxcso wont work on JPCSP

### ISSUE THREAD

**Issue by MojoJojoDojo** [jpcsp/jpcsp#480]
As the title says.
I am talking about maxcso before this commit was made https://github.com/unknownbrackets/maxcso/commit/161f99d81f81716943069387bb0234ce5a1355b3
and on the latest stable release.
It's basically any cso so I don't think logs are required.

**Comment by MojoJojoDojo** [comment]
Actually it wont matter if its the latest commit (libdeflate disabled) or not.
It also wont matter if block size is 2048 as suggested here:
https://github.com/unknownbrackets/maxcso/issues/55#issuecomment-980096072

**Comment by gid15** [comment]
Could you please generate such a CSO from the cube.iso and share it? That would be easier for me to debug :-)

**Comment by MojoJojoDojo** [comment]
> Could you please generate such a CSO from the cube.iso and share it? That would be easier for me to debug :-)

Roger that.
[cube-cso.zip](https://github.com/jpcsp/jpcsp/files/7610740/cube-cso.zip)

This got 3 cubes.
cube was done with the default maxcso.
cube2 is the one where i have both libdeflate off and block size 2048.
And I generated cube3 with only libdeflate off.

**Comment by gid15** [comment]
Should now be fixed by commit d32e126.
Thank you for pointing this out!

**Comment by MojoJojoDojo** [comment]
Cool that gonna help me for testing stuff now.
Closing it.

**Comment by unknownbrackets** [comment]
Good fix.  I'll just note that maxcso also supports creating alternate block sizes (i.e. block size != sector size), which is still unsupported afaict.  The "sector size" field is actually the block size.  See here:

https://github.com/unknownbrackets/maxcso/blob/master/README_CSO.md

Basically, this means you might have a 16 KB block which contains 8 sectors, combined to improve compression ratio.  That said, most PSP CFW don't support larger block sizes either, for memory size reasons.

-[Unknown]
