### ISSUE TITLE
firmware 6.61 not booting for PSP Model 3000

### ISSUE THREAD

**Issue by Narugakuruga** [jpcsp/jpcsp#483]
I try to install firmware 6.61 and was successful. But rebooting throw an error "psp system setting is corrupted" (psp 1000 mode)
Or jpscp can't find executable in psp 3000 mode
![Uploading [WH(R[2KE)Z%WM62]_YZGWD.png…]()

**Comment by Masamune3210** [comment]
Your picture didn't upload....

**Comment by gid15** [comment]
Could you please set the log (menu Debug / Tools / Logger / Show Logger) to the INFO level, then reproduce the issue and post the generated log.txt file.
Without having much information, I would say that the most probable reason is that you are using a very old version of Jpcsp.

**Comment by Narugakuruga** [comment]
I'm sorry I didn't post the log
![WH(R 2KE)Z%WM62 _YZGWD](https://user-images.githubusercontent.com/31060534/145148847-cba38b26-33a6-442a-9dd5-054a4f3cdc5b.png)

**Comment by Narugakuruga** [comment]
[log.txt](https://github.com/jpcsp/jpcsp/files/7673415/log.txt)
![JPCSP](https://user-images.githubusercontent.com/31060534/145149410-3434d817-e48a-4e3e-9855-18e753d6f226.png)
I used the latest build. Sorry if I made a mistake. I really appreciate your LLE development work😀

**Comment by gid15** [comment]
OK, I can reproduce the issue when setting the PSP Model to "PSP-3000 (Brite, 9th Generation)". I've not yet well tested all the PSP Models and I will need some time to fix this issue.
If you want, you can try out with the PSP Model "PSP-1000 (Fat)", this is the test case which is the most complete. You will need to delete the content of the flash0 directory and restart the installation with the PSP Installer 6.61.

**Comment by gid15** [comment]
My tests for a PSP-3000 model were now successful with revision a8dc7bf. Could you please try it out?
Thank you!

**Comment by Narugakuruga** [comment]
Thank you so much ! I will test it APAP. It's really a fortune to enjoy XMB again

**Comment by Narugakuruga** [comment]
Thank you so much ! I will test it APAP. It's really a fortune to enjoy XMB again

**Comment by Narugakuruga** [comment]
It's perfectly working now！ thank you!
