### ISSUE TITLE
PSP Keyboard is not working properly

### ISSUE THREAD

**Issue by MojoJojoDojo** [jpcsp/jpcsp#488]
This is an issue that I found which happens on the game Twisted Metal Head On but could affect other games as well.
When you enter Infrastructure mode , the keyboard only lets you input the username.
It should continue prompt you to enter the password right after inputting the username but for some reason it wont continue past it.
Log made with INFO is here:
[log.zip](https://github.com/jpcsp/jpcsp/files/7920986/log.zip)

**Comment by MojoJojoDojo** [comment]
BTW the issue is seperate from the one when you can't make the message box prompt to show up sometimes after trying to get to the keyboard.https://github.com/jpcsp/jpcsp/issues/472#issuecomment-917451692

**Comment by gid15** [comment]
I found out that the sceUtilityOsk methods can support the entry of multiple data into a single call. This might be used by this game to enter both the username and password.
Does the revision d1dff2b help?

**Comment by MojoJojoDojo** [comment]
Yep seems to work now so time to close the issue.
