### ISSUE TITLE
CHD support

### ISSUE THREAD

**Issue by ghost** [jpcsp/jpcsp#501]
Adding CHD support for PSP games.
By using libchd : 
https://github.com/rtissera/libchdr

Or another appropriate library.

**Comment by gid15** [comment]
Could you convert the cube.iso provided in Jpcsp to CHD, as an example?

**Comment by sum2012** [comment]
convert iso to chd: Use chdman
https://wiki.recalbox.com/en/tutorials/utilities/rom-conversion/chdman
command (batch file in windows ):
chdman createcd -o cube.chd -i cube.iso
[cube.zip](https://github.com/jpcsp/jpcsp/files/9125672/cube.zip)
(Not tested for cube.chd)

**Comment by MojoJojoDojo** [comment]
> convert iso to chd: Use chdman https://wiki.recalbox.com/en/tutorials/utilities/rom-conversion/chdman command (batch file in windows ): chdman createcd -o cube.chd -i cube.iso [cube.zip](https://github.com/jpcsp/jpcsp/files/9125672/cube.zip) (Not tested for cube.chd)

Nice , it's even lower then how I created it before with maxcso.

**Comment by gid15** [comment]
Should now be implemented in 58eaca3

**Comment by gid15** [comment]
Closing
