### ISSUE TITLE
sceIoOpen not supposed to create parent folder automatically when not existed

### ISSUE THREAD

**Issue by ANR2ME** [jpcsp/jpcsp#504]
I have this small sceHttp sample taken from https://github.com/vitasdk/samples/blob/master/net_http/src/main.c and modified to be buildable using pspsdk
[http.zip](https://github.com/jpcsp/jpcsp/files/9892673/http.zip)
Which supposed to download index.html file from http://barooney.com/ and saving it to `ms0:/data/index.html` (originally `ux0:data/index.html` on vita), i also tested it with `ms0:data/index.html` and have the same result.

When i tested the EBOOT.PBP on jpcsp-4f87e9c-windows-amd64 from @lightfirst , it created the `data` folder automatically when not existed and successfully created the index.html file, while on PPSSPP sceIoOpen failed to create the file and returning 0x80010002
According to this test https://github.com/hrydgard/pspautotests/pull/233 PPSSPP shows the correct behavior.

Edit: i've also tested this on the latest artifact from github action (ie. jpcsp-8f89341-windows-amd64)

**Comment by gid15** [comment]
Thank you for pointing out! I will check it.
From the history log, I see that the incorrect code was introduced 11 years ago...

**Comment by gid15** [comment]
Should now be fixed. Sorry for the late reply, I was busy with other topics.
